### ISSUE TITLE
How is the IPC itself implemented?

### ISSUE THREAD

**Issue by etodanik** [xplpc/xplpc#45]
I casually went through the code. Overall looks like a super useful project, but it was non trivial to understand the architecture on a more technical level.

Are you creating a shared memory space? Memory mapped file? Are you communicating via named-pipes/sockets?

EDIT:
I think I misunderstood somewhat, this isn't IPC, it's more like a bridge to bind languages (serialize / deserialize).

Very useful in potential! Wish you luck! Would love to try it out sometime on a real project.

**Comment by paulocoutinhox** [comment]
Hi,

Thanks for all.

My english is not good. If you see and better words that explain what project do, you can post here.

The architecture is simple and consist in some bridge code between languages exchanging some serialized data.
